### ISSUE TITLE
Compile game_data json file

### ISSUE THREAD

**Issue by Gnihc42** [Kengxxiao/ArknightsGameData#22]
Hello, I would like to ask if it's possible to compile the character_table.json back to it's original Unity TextAsset format?

**Comment by Kengxxiao** [comment]
In CN server, I think you can deserialize original character_table assetbundle via flatbuffers compiler (check schema in FBS repo) and modify the result, serialize it back. I do not know if it works.
You should pay attention to the signature check of data files in game, you need to check how to bypass it by yourself.

**Comment by Gnihc42** [comment]
How do I serialize, deserialize it though?
I got flatc installed. but i dont really know how to use it
![image](https://github.com/Kengxxiao/ArknightsGameData/assets/114859565/a18e541f-9b73-4acb-8813-df33da7d7f15)

**Comment by Gnihc42** [comment]
Or can you show me how your bot update these files instead?
