### ISSUE TITLE
Future of zh_TW

### ISSUE THREAD

**Issue by jaywyeee** [Kengxxiao/ArknightsGameData#23]
In 4fb0b44, zh_TW's data was deleted. While that version has not been updated since [January 2022](https://github.com/Kengxxiao/ArknightsGameData/commits/2cb678a073c0a9de2f1454c4178eabbc578dec58/zh_TW), are there any thoughts of resuming to update it from now on? It might not have much practical use but I think that it would be nice to have a complete archive.

**Comment by Kengxxiao** [comment]
NO.
Actually it will be YES at the beginning. But after i finished bot works on CN 2.0 and i tried to test it on Longcheng server it cannot work, although it can work correctly on all other servers, so i gave it up completely.
You can check other repos like [aelurum/ArknightsGameData](https://github.com/aelurum/ArknightsGameData) which is working on this for other solutions.

**Comment by jaywyeee** [comment]
Aha, I see. Thanks for all your hard work!
