### ISSUE TITLE
EN level_act4d0_04.json file corrupted

### ISSUE THREAD

**Issue by Awedtan** [Kengxxiao/ArknightsGameData#24]
The file at [en_US/gamedata/levels/activities/act4d0/level_act4d0_05.json](https://github.com/Kengxxiao/ArknightsGameData/blob/master/en_US/gamedata/levels/activities/act4d0/level_act4d0_05.json) seems to be corrupted or malformed, could you take a look into this? The file was last updated 8 months ago, before that change it seemed to be normal.

**Comment by Kengxxiao** [comment]
Fixed.
