### ISSUE TITLE
干员的上线时间

### ISSUE THREAD

**Issue by Cyletix** [Kengxxiao/ArknightsGameData#26]
请问一下干员的上线时间的数据在哪里, 我找了很久都没找到

**Comment by dogdie233** [comment]
> 请问一下干员的上线时间的数据在哪里, 我找了很久都没找到

游戏数据怎么会有这种东西。
如果你想要粗略的不准确的时间可以看commit时间(?

**Comment by Yjun233** [comment]
prts wiki有这个页面
https://prts.wiki/w/干员上线时间一览
