### ISSUE TITLE
KR & EN & JP

### ISSUE THREAD

**Issue by arkngithsad** [Kengxxiao/ArknightsGameData#28]
Did the global server change the file with a flatbuffer?

**Comment by nikitazero678** [comment]
Most likely, because normally this does not take this long.

**Comment by Kengxxiao** [comment]
Check [ArknightsGameData_YoStar](https://github.com/Kengxxiao/ArknightsGameData_YoStar) and updated README here.

**Comment by arkngithsad** [comment]
Thanks
